# Generated by Django 4.2.5 on 2023-09-24 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numdocumento', models.IntegerField()),
                ('numlegajo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sueldo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('unidad_med', models.PositiveIntegerField(choices=[(2, 'unidad'), (1, 'm2')])),
                ('contenido_neto', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.TextField()),
                ('baja', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('unidad_medida', models.PositiveIntegerField(choices=[(2, 'unidad'), (1, 'm2')])),
                ('precio', models.IntegerField()),
                ('insumos', models.ManyToManyField(to='core.insumo')),
                ('maquinarias', models.ManyToManyField(to='core.maquinaria')),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Correcion'), (2, 'Suspension')])),
                ('nroSancion', models.IntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.localidad'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo', models.PositiveIntegerField(choices=[(2, 'Habitual'), (1, 'Ocacional')])),
                ('tipopersona', models.PositiveIntegerField(choices=[(2, 'Habitual'), (1, 'Ocacional')])),
                ('cuil', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='CantInsumoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.insumo')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tiposervicio')),
            ],
        ),
    ]
