# Generated by Django 4.2.5 on 2023-09-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tipopersona',
            new_name='tipoPersona',
        ),
    ]
