# Generated by Django 4.2.5 on 2025-08-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Habitual'), (1, 'Ocacional')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.PositiveIntegerField(choices=[(1, 'Particular'), (2, 'Juridico')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(3, 'ml'), (4, 'Lts'), (2, 'Kg'), (1, 'gr')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Suspension'), (1, 'Correcion')]),
        ),
    ]
