# Generated by Django 4.2.5 on 2025-07-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Habitual'), (1, 'Ocacional')], default=1),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(1, 'gr'), (2, 'Kg'), (3, 'ml'), (4, 'Lts')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Correcion'), (2, 'Suspension')]),
        ),
    ]
