# Generated by Django 4.2.5 on 2025-07-30 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_cliente_tipo_alter_insumo_unidad_med_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Ocacional'), (2, 'Habitual')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.PositiveIntegerField(choices=[(1, 'Particular'), (2, 'Juridico')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(2, 'Kg'), (3, 'ml'), (1, 'gr'), (4, 'Lts')]),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='unidad_medida',
            field=models.PositiveIntegerField(choices=[(1, 'm2'), (2, 'unidad')]),
        ),
    ]
