# Generated by Django 4.2.5 on 2023-09-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_tipopersona_cliente_tipopersona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localidad',
            old_name='cd',
            new_name='cp',
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Suspension'), (1, 'Correcion')]),
        ),
    ]
