# Generated by Django 4.2.5 on 2023-10-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_tipo_alter_cliente_tipopersona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Ocacional'), (2, 'Habitual')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.PositiveIntegerField(choices=[(2, 'Juridico'), (1, 'Particular')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(3, 'ml'), (2, 'Kg'), (1, 'gr'), (4, 'Lts')]),
        ),
    ]
