# Generated by Django 4.2.5 on 2025-07-30 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_cliente_usuario_alter_cliente_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(3, 'ml'), (1, 'gr'), (2, 'Kg'), (4, 'Lts')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Suspension'), (1, 'Correcion')]),
        ),
    ]
