# Generated by Django 4.2.5 on 2025-04-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_tipopersona_alter_insumo_unidad_med_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Ocacional'), (2, 'Habitual')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.PositiveIntegerField(choices=[(2, 'Juridico'), (1, 'Particular')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(1, 'gr'), (2, 'Kg'), (4, 'Lts'), (3, 'ml')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Correcion'), (2, 'Suspension')]),
        ),
    ]
