# Generated by Django 4.2.5 on 2023-10-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_direccion_alter_cliente_tipopersona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.PositiveIntegerField(choices=[(1, 'Particular'), (2, 'Juridico')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(1, 'gr'), (4, 'Lts'), (2, 'Kg'), (3, 'ml')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Correcion'), (2, 'Suspension')]),
        ),
    ]
