# Generated by Django 4.2.5 on 2023-09-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cd_localidad_cp_alter_sancion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.PositiveIntegerField(choices=[(1, 'm2'), (2, 'unidad')]),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='unidad_medida',
            field=models.PositiveIntegerField(choices=[(1, 'm2'), (2, 'unidad')]),
        ),
    ]
