# Generated by Django 4.2.5 on 2023-10-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_empleado_numlegajo_alter_cliente_tipopersona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='baja',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='baja',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(1, 'gr'), (3, 'ml'), (2, 'Kg'), (4, 'Lts')]),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='baja',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Correcion'), (2, 'Suspension')]),
        ),
    ]
