# Generated by Django 4.2.5 on 2025-06-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_insumo_unidad_med_alter_sancion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Habitual'), (1, 'Ocacional')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.PositiveIntegerField(choices=[(1, 'Particular'), (2, 'Juridico')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(4, 'Lts'), (2, 'Kg'), (3, 'ml'), (1, 'gr')]),
        ),
    ]
