# Generated by Django 4.2.5 on 2023-10-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente_activo_empleado_activo_insumo_baja_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='baja',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='baja',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='tiposervicio',
            old_name='baja',
            new_name='activo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Habitual'), (1, 'Ocacional')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.PositiveIntegerField(choices=[(2, 'Juridico'), (1, 'Particular')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(3, 'ml'), (4, 'Lts'), (2, 'Kg'), (1, 'gr')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Suspension'), (1, 'Correcion')]),
        ),
    ]
