# Generated by Django 4.2.5 on 2025-02-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cliente_tipopersona_alter_insumo_unidad_med'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(3, 'ml'), (1, 'gr'), (2, 'Kg'), (4, 'Lts')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='diasSuspension',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Correcion'), (2, 'Suspension')]),
        ),
    ]
