# Generated by Django 4.2.5 on 2023-10-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_baja_insumo_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuil',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Ocacional'), (2, 'Habitual')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.PositiveIntegerField(choices=[(1, 'Particular'), (2, 'Juridico')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numDNI',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(3, 'ml'), (1, 'gr'), (2, 'Kg'), (4, 'Lts')]),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='unidad_medida',
            field=models.PositiveIntegerField(choices=[(2, 'unidad'), (1, 'm2')]),
        ),
    ]
