# Generated by Django 4.2.5 on 2023-10-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cliente_cuil_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuil',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.PositiveIntegerField(choices=[(2, 'Juridico'), (1, 'Particular')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(3, 'ml'), (1, 'gr'), (4, 'Lts'), (2, 'Kg')]),
        ),
    ]
