# Generated by Django 4.2.5 on 2023-11-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_insumo_unidad_med_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sueldo_basico',
            field=models.IntegerField(default=58000),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(1, 'gr'), (3, 'ml'), (2, 'Kg'), (4, 'Lts')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Correcion'), (2, 'Suspension')]),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='unidad_medida',
            field=models.PositiveIntegerField(choices=[(1, 'm2'), (2, 'unidad')]),
        ),
    ]
