# Generated by Django 4.2.5 on 2023-11-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_empleado_sueldo_basico_alter_cliente_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='activo',
        ),
        migrations.AddField(
            model_name='insumo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Deshabilitado'), (2, 'Habilitado')], default=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Habitual'), (1, 'Ocacional')], default=1),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(3, 'ml'), (2, 'Kg'), (1, 'gr'), (4, 'Lts')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Suspension'), (1, 'Correcion')]),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='unidad_medida',
            field=models.PositiveIntegerField(choices=[(2, 'unidad'), (1, 'm2')]),
        ),
    ]
