# Generated by Django 4.2.5 on 2023-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_insumo_activo_insumo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.PositiveIntegerField(choices=[(1, 'Particular'), (2, 'Juridico')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.IntegerField(choices=[(2, 'Habilitado'), (1, 'Deshabilitado')], default=2),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(4, 'Lts'), (3, 'ml'), (1, 'gr'), (2, 'Kg')]),
        ),
    ]
