# Generated by Django 4.2.5 on 2023-11-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_cliente_tipo_alter_insumo_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='activo',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Habitual'), (1, 'Ocacional')], default=1),
        ),
    ]
