# Generated by Django 4.2.5 on 2023-11-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_insumo_unidad_med_alter_sancion_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(4, 'Lts'), (3, 'ml'), (2, 'Kg'), (1, 'gr')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Suspension'), (1, 'Correcion')]),
        ),
    ]
