# Generated by Django 4.2.5 on 2023-11-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_insumo_unidad_med_alter_sancion_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='estado',
            new_name='activo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Habitual'), (1, 'Ocacional')], default=1),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(4, 'Lts'), (1, 'gr'), (3, 'ml'), (2, 'Kg')]),
        ),
    ]
