# Generated by Django 4.2.5 on 2023-11-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_activo_empleado_estado_alter_cliente_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.PositiveIntegerField(choices=[(1, 'Particular'), (2, 'Juridico')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(2, 'Kg'), (3, 'ml'), (1, 'gr'), (4, 'Lts')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Suspension'), (1, 'Correcion')]),
        ),
    ]
