# Generated by Django 4.2.5 on 2023-11-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cliente_tipo_alter_cliente_tipopersona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(4, 'Lts'), (1, 'gr'), (2, 'Kg'), (3, 'ml')]),
        ),
    ]
