# Generated by Django 4.2.5 on 2023-12-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_cliente_tipopersona_alter_insumo_unidad_med'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Habitual'), (1, 'Ocacional')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.PositiveIntegerField(choices=[(2, 'Juridico'), (1, 'Particular')]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_med',
            field=models.IntegerField(choices=[(4, 'Lts'), (1, 'gr'), (2, 'Kg'), (3, 'ml')]),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='maquinarias',
            field=models.ManyToManyField(null=True, to='core.maquinaria'),
        ),
    ]
