# Generated by Django 4.2.5 on 2023-11-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0018_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
        ('core', '0022_alter_insumo_unidad_med'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_total', models.IntegerField()),
                ('fechaEmision', models.DateField(auto_now=True)),
                ('formaPago', models.PositiveIntegerField(choices=[(3, 'Transferencia'), (2, 'Cheque'), (1, 'Efectivo')])),
                ('fechaPago', models.DateField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
                ('detalle_tip_servicio', models.ManyToManyField(to='factura.detalle_factura')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servicio.servicio')),
            ],
        ),
    ]
