# Generated by Django 4.2.5 on 2025-07-20 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField(choices=[(3, 'Mensual'), (2, 'Unica'), (1, 'Seña')])),
                ('importe', models.IntegerField()),
                ('fechaEmision', models.DateField(auto_now=True)),
                ('fecha_vencimiento', models.DateField(null=True)),
                ('periodoServicio', models.IntegerField(null=True)),
                ('formaPago', models.PositiveIntegerField(choices=[(3, 'Transferencia'), (2, 'Cheque'), (1, 'Efectivo')], null=True)),
                ('fechaPago', models.DateField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servicio.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('tipo_servicio_Unit', models.CharField(max_length=50)),
                ('precio_tipo_servicio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_empleados', models.IntegerField()),
                ('importe_mano_obra', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
            ],
        ),
    ]
