# Generated by Django 4.2.5 on 2023-12-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(3, 'Transferencia'), (1, 'Efectivo'), (2, 'Cheque')], null=True),
        ),
    ]
