# Generated by Django 4.2.5 on 2025-07-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(2, 'Cheque'), (1, 'Efectivo'), (3, 'Transferencia')], null=True),
        ),
    ]
