# Generated by Django 4.2.5 on 2024-01-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(1, 'Efectivo'), (3, 'Transferencia'), (2, 'Cheque')], null=True),
        ),
    ]
