# Generated by Django 4.2.5 on 2025-08-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_alter_factura_formapago_alter_factura_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Seña'), (2, 'Unica'), (3, 'Mensual')]),
        ),
    ]
