# Generated by Django 4.2.5 on 2025-08-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_alter_factura_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(1, 'Efectivo'), (3, 'Transferencia'), (2, 'Cheque')], null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Unica'), (1, 'Seña'), (3, 'Mensual')]),
        ),
    ]
