# Generated by Django 4.2.5 on 2023-12-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_alter_factura_formapago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='importe_total',
            new_name='importe',
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Unica'), (1, 'Seña'), (3, 'Mensual')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(2, 'Cheque'), (3, 'Transferencia'), (1, 'Efectivo')]),
        ),
    ]
