# Generated by Django 4.2.5 on 2023-12-02 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_cliente_tipopersona_alter_insumo_unidad_med_and_more'),
        ('servicio', '0020_alter_frecuencia_dia_alter_servicio_estado'),
        ('factura', '0003_alter_factura_formapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaSeña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.IntegerField()),
                ('fechaEmision', models.DateField(auto_now=True)),
                ('formaPago', models.PositiveIntegerField(choices=[(1, 'Efectivo'), (3, 'Transferencia')])),
                ('fechaPago', models.DateField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servicio.servicio')),
            ],
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='importe_total',
            new_name='importe',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='detalle_tip_servicio',
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='periodoServicio',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='fechaEmision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(1, 'Efectivo'), (2, 'Cheque'), (3, 'Transferencia')], null=True),
        ),
        migrations.DeleteModel(
            name='Detalle_Factura',
        ),
    ]
