# Generated by Django 4.2.5 on 2023-12-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_rename_importe_total_factura_importe_factura_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(3, 'Transferencia'), (1, 'Efectivo'), (2, 'Cheque')]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Seña'), (3, 'Mensual'), (2, 'Unica')]),
        ),
    ]
