# Generated by Django 4.2.5 on 2025-08-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_alter_factura_formapago_alter_factura_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(1, 'Efectivo'), (2, 'Cheque'), (3, 'Transferencia')], null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(3, 'Mensual'), (2, 'Unica'), (1, 'Seña')]),
        ),
    ]
