# Generated by Django 4.2.5 on 2023-12-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_facturaseña_rename_importe_total_factura_importe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(3, 'Transferencia'), (2, 'Cheque'), (1, 'Efectivo')], null=True),
        ),
        migrations.AlterField(
            model_name='facturaseña',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(3, 'Transferencia'), (1, 'Efectivo')]),
        ),
    ]
