# Generated by Django 4.2.5 on 2023-12-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_alter_factura_formapago_alter_facturaseña_formapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(3, 'Mensual'), (1, 'Seña'), (2, 'Unica')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(2, 'Cheque'), (1, 'Efectivo'), (3, 'Transferencia')], null=True),
        ),
        migrations.CreateModel(
            name='Detalle_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('tipo_servicio_Unit', models.CharField(max_length=50)),
                ('precio_tipo_servicio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_empleados', models.IntegerField()),
                ('importe_mano_obra', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
            ],
        ),
    ]
