# Generated by Django 4.2.5 on 2023-12-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_alter_factura_formapago_alter_factura_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='detalle_tip_servicio',
        ),
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(3, 'Transferencia'), (2, 'Cheque'), (1, 'Efectivo')]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Seña'), (2, 'Unica'), (3, 'Mensual')]),
        ),
    ]
