# Generated by Django 4.2.5 on 2025-06-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_alter_factura_formapago_alter_factura_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fechaEmision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(2, 'Cheque'), (1, 'Efectivo'), (3, 'Transferencia')], null=True),
        ),
    ]
