# Generated by Django 4.2.5 on 2023-12-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_remove_factura_detalle_tip_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.PositiveIntegerField(choices=[(2, 'Cheque'), (1, 'Efectivo'), (3, 'Transferencia')], null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Unica'), (1, 'Seña'), (3, 'Mensual')]),
        ),
    ]
