# Generated by Django 4.2.5 on 2025-07-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_alter_factura_formapago_alter_factura_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(3, 'Mensual'), (1, 'Seña'), (2, 'Unica')]),
        ),
    ]
