# Generated by Django 4.2.5 on 2025-07-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(6, 'Sabado'), (5, 'Viernes'), (3, 'Miercoles'), (2, 'Martes'), (4, 'Jueves'), (1, 'Lunes')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Vencido'), (1, 'Presupuestado'), (5, 'Suspendido'), (7, 'Cancelado'), (6, 'Finalizado'), (3, 'Contratado'), (4, 'En Curso')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Eventual'), (2, 'Determinado')]),
        ),
    ]
