# Generated by Django 4.2.5 on 2025-08-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(2, 'Martes'), (4, 'Jueves'), (6, 'Sabado'), (3, 'Miercoles'), (1, 'Lunes'), (5, 'Viernes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(2, 'Tarde'), (3, 'Noche'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(6, 'Finalizado'), (3, 'Contratado'), (1, 'Presupuestado'), (5, 'Suspendido'), (2, 'Vencido'), (4, 'En Curso'), (7, 'Cancelado')]),
        ),
    ]
