# Generated by Django 4.2.5 on 2023-10-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(6, 'Sabado'), (2, 'Martes'), (5, 'Viernes'), (4, 'Jueves'), (3, 'Miercoles'), (1, 'Lunes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(2, 'Tarde'), (3, 'Noche'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Presupuestodo'), (2, 'Vencido'), (5, 'Suspendido'), (6, 'Finalizado'), (3, 'Contratado'), (4, 'En Curso'), (7, 'Cancelado')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Eventual'), (2, 'Determinado')]),
        ),
    ]
