# Generated by Django 4.2.5 on 2024-01-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(2, 'Martes'), (4, 'Jueves'), (1, 'Lunes'), (6, 'Sabado'), (3, 'Miercoles'), (5, 'Viernes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Presupuestado'), (3, 'Contratado'), (2, 'Vencido'), (7, 'Cancelado'), (4, 'En Curso'), (5, 'Suspendido'), (6, 'Finalizado')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Eventual'), (2, 'Determinado')]),
        ),
    ]
