# Generated by Django 4.2.5 on 2025-04-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(1, 'Lunes'), (3, 'Miercoles'), (5, 'Viernes'), (6, 'Sabado'), (2, 'Martes'), (4, 'Jueves')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Vencido'), (5, 'Suspendido'), (1, 'Presupuestado'), (7, 'Cancelado'), (6, 'Finalizado'), (3, 'Contratado'), (4, 'En Curso')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Determinado'), (1, 'Eventual')]),
        ),
    ]
