# Generated by Django 4.2.5 on 2025-07-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_frecuencia_dia_alter_servicio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(2, 'Martes'), (5, 'Viernes'), (4, 'Jueves'), (1, 'Lunes'), (6, 'Sabado'), (3, 'Miercoles')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(2, 'Tarde'), (1, 'Mañana'), (3, 'Noche')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(7, 'Cancelado'), (3, 'Contratado'), (2, 'Vencido'), (4, 'En Curso'), (6, 'Finalizado'), (1, 'Presupuestado'), (5, 'Suspendido')]),
        ),
    ]
