# Generated by Django 4.2.5 on 2025-08-13 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sancion_id_sancion_descripcion_and_more'),
        ('servicio', '0002_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('A', 'Asistió'), ('F', 'Faltó')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='servicio.servicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado'),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='fecha_reclamo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empleado'),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(5, 'Viernes'), (3, 'Miercoles'), (2, 'Martes'), (4, 'Jueves'), (6, 'Sabado'), (1, 'Lunes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(2, 'Tarde'), (1, 'Mañana'), (3, 'Noche')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(4, 'En Curso'), (1, 'Presupuestado'), (7, 'Cancelado'), (5, 'Suspendido'), (6, 'Finalizado'), (3, 'Contratado'), (2, 'Vencido')]),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('fecha', 'empleado', 'servicio')},
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='hora_salida',
        ),
    ]
