# Generated by Django 4.2.5 on 2023-10-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(1, 'Lunes'), (6, 'Sabado'), (5, 'Viernes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(1, 'Mañana'), (3, 'Noche'), (2, 'Tarde')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(4, 'En Curso'), (5, 'Suspendido'), (6, 'Finalizado'), (7, 'Cancelado'), (1, 'Presupuestodo'), (2, 'Vencido'), (3, 'Contratado')]),
        ),
    ]
