# Generated by Django 4.2.5 on 2023-10-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(3, 'Contratado'), (7, 'Cancelado'), (5, 'Suspendido'), (1, 'Presupuestodo'), (4, 'En Curso'), (6, 'Finalizado'), (2, 'Vencido')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Determinado'), (1, 'Eventual')]),
        ),
    ]
