# Generated by Django 4.2.5 on 2025-07-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(6, 'Sabado'), (2, 'Martes'), (1, 'Lunes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(2, 'Tarde'), (3, 'Noche'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Vencido'), (4, 'En Curso'), (3, 'Contratado'), (7, 'Cancelado'), (5, 'Suspendido'), (6, 'Finalizado'), (1, 'Presupuestado')]),
        ),
    ]
