# Generated by Django 4.2.5 on 2023-11-02 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cliente_tipo_alter_cliente_tipopersona_and_more'),
        ('servicio', '0003_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frecuencia',
            name='servicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='frecuencias',
            field=models.ManyToManyField(to='servicio.frecuencia'),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(2, 'Martes'), (4, 'Jueves'), (1, 'Lunes'), (3, 'Miercoles'), (6, 'Sabado'), (5, 'Viernes')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(3, 'Contratado'), (7, 'Cancelado'), (5, 'Suspendido'), (1, 'Presupuestodo'), (6, 'Finalizado'), (4, 'En Curso'), (2, 'Vencido')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Determinado'), (1, 'Eventual')]),
        ),
        migrations.CreateModel(
            name='CantServicioTipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servicio.servicio')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tiposervicio')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipoServicios',
            field=models.ManyToManyField(through='servicio.CantServicioTipoServicio', to='core.tiposervicio'),
        ),
    ]
