# Generated by Django 4.2.5 on 2025-08-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_asistencia_options_asistencia_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(3, 'Miercoles'), (6, 'Sabado'), (5, 'Viernes'), (1, 'Lunes'), (4, 'Jueves'), (2, 'Martes')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(7, 'Cancelado'), (3, 'Contratado'), (5, 'Suspendido'), (6, 'Finalizado'), (2, 'Vencido'), (1, 'Presupuestado'), (4, 'En Curso')]),
        ),
    ]
