# Generated by Django 4.2.5 on 2025-04-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_frecuencia_dia_alter_servicio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(4, 'Jueves'), (1, 'Lunes'), (3, 'Miercoles'), (2, 'Martes'), (6, 'Sabado'), (5, 'Viernes')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(3, 'Contratado'), (2, 'Vencido'), (4, 'En Curso'), (6, 'Finalizado'), (7, 'Cancelado'), (5, 'Suspendido'), (1, 'Presupuestado')]),
        ),
    ]
