# Generated by Django 4.2.5 on 2025-08-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_alter_frecuencia_dia_alter_servicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(6, 'Sabado'), (1, 'Lunes'), (3, 'Miercoles'), (4, 'Jueves'), (2, 'Martes'), (5, 'Viernes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(2, 'Tarde'), (3, 'Noche'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Presupuestado'), (7, 'Cancelado'), (6, 'Finalizado'), (4, 'En Curso'), (2, 'Vencido'), (3, 'Contratado'), (5, 'Suspendido')]),
        ),
    ]
