# Generated by Django 4.2.5 on 2025-06-20 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cliente_tipo_alter_cliente_tipopersona_and_more'),
        ('servicio', '0005_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='localidad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.localidad'),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(5, 'Viernes'), (3, 'Miercoles'), (4, 'Jueves'), (6, 'Sabado'), (2, 'Martes'), (1, 'Lunes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(3, 'Noche'), (1, 'Mañana'), (2, 'Tarde')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Vencido'), (3, 'Contratado'), (5, 'Suspendido'), (7, 'Cancelado'), (1, 'Presupuestado'), (4, 'En Curso'), (6, 'Finalizado')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Determinado'), (1, 'Eventual')]),
        ),
    ]
