# Generated by Django 4.2.5 on 2023-10-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(1, 'Lunes'), (3, 'Miercoles'), (2, 'Martes'), (5, 'Viernes'), (4, 'Jueves'), (6, 'Sabado')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(3, 'Noche'), (2, 'Tarde'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Vencido'), (4, 'En Curso'), (6, 'Finalizado'), (5, 'Suspendido'), (1, 'Presupuestodo'), (7, 'Cancelado'), (3, 'Contratado')]),
        ),
    ]
