# Generated by Django 4.2.5 on 2023-11-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(4, 'Jueves'), (6, 'Sabado'), (1, 'Lunes'), (5, 'Viernes'), (3, 'Miercoles'), (2, 'Martes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(3, 'Noche'), (1, 'Mañana'), (2, 'Tarde')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(5, 'Suspendido'), (6, 'Finalizado'), (4, 'En Curso'), (2, 'Vencido'), (3, 'Contratado'), (1, 'Presupuestodo'), (7, 'Cancelado')]),
        ),
    ]
