# Generated by Django 4.2.5 on 2025-08-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(2, 'Martes'), (1, 'Lunes'), (5, 'Viernes'), (3, 'Miercoles'), (6, 'Sabado'), (4, 'Jueves')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(3, 'Noche'), (1, 'Mañana'), (2, 'Tarde')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Vencido'), (6, 'Finalizado'), (5, 'Suspendido'), (7, 'Cancelado'), (1, 'Presupuestado'), (3, 'Contratado'), (4, 'En Curso')]),
        ),
    ]
