# Generated by Django 4.2.5 on 2023-10-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(6, 'Sabado'), (3, 'Miercoles'), (1, 'Lunes'), (4, 'Jueves'), (5, 'Viernes'), (2, 'Martes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Vencido'), (1, 'Presupuestodo'), (5, 'Suspendido'), (7, 'Cancelado'), (4, 'En Curso'), (6, 'Finalizado'), (3, 'Contratado')]),
        ),
    ]
