# Generated by Django 4.2.5 on 2025-07-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_servicio_localidad_alter_frecuencia_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(5, 'Viernes'), (4, 'Jueves'), (1, 'Lunes'), (6, 'Sabado'), (3, 'Miercoles'), (2, 'Martes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(4, 'En Curso'), (1, 'Presupuestado'), (6, 'Finalizado'), (5, 'Suspendido'), (2, 'Vencido'), (7, 'Cancelado'), (3, 'Contratado')]),
        ),
    ]
