# Generated by Django 4.2.5 on 2023-11-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(3, 'Miercoles'), (4, 'Jueves'), (1, 'Lunes'), (2, 'Martes'), (5, 'Viernes'), (6, 'Sabado')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(3, 'Noche'), (2, 'Tarde'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(7, 'Cancelado'), (2, 'Vencido'), (6, 'Finalizado'), (1, 'Presupuestodo'), (5, 'Suspendido'), (4, 'En Curso'), (3, 'Contratado')]),
        ),
    ]
