# Generated by Django 4.2.5 on 2023-11-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frecuencia',
            name='horaFin',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='horaInicio',
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(1, 'Lunes'), (3, 'Miercoles'), (5, 'Viernes'), (4, 'Jueves'), (2, 'Martes'), (6, 'Sabado')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(2, 'Tarde'), (1, 'Mañana'), (3, 'Noche')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(3, 'Contratado'), (7, 'Cancelado'), (4, 'En Curso'), (1, 'Presupuestodo'), (5, 'Suspendido'), (6, 'Finalizado'), (2, 'Vencido')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Eventual'), (2, 'Determinado')]),
        ),
    ]
