# Generated by Django 4.2.5 on 2023-10-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(5, 'Viernes'), (4, 'Jueves'), (3, 'Miercoles'), (2, 'Martes'), (1, 'Lunes'), (6, 'Sabado')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(1, 'Mañana'), (3, 'Noche'), (2, 'Tarde')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(5, 'Suspendido'), (1, 'Presupuestodo'), (7, 'Cancelado'), (6, 'Finalizado'), (2, 'Vencido'), (3, 'Contratado'), (4, 'En Curso')]),
        ),
    ]
