# Generated by Django 4.2.5 on 2023-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cliente_tipopersona_alter_insumo_estado_and_more'),
        ('servicio', '0008_remove_frecuencia_horafin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(2, 'Martes'), (3, 'Miercoles'), (5, 'Viernes'), (6, 'Sabado'), (1, 'Lunes'), (4, 'Jueves')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='empleado',
            field=models.ManyToManyField(null=True, to='core.empleado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(5, 'Suspendido'), (6, 'Finalizado'), (2, 'Vencido'), (3, 'Contratado'), (1, 'Presupuestodo'), (7, 'Cancelado'), (4, 'En Curso')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_cancelada',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_finaliza',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Determinado'), (1, 'Eventual')]),
        ),
    ]
