# Generated by Django 4.2.5 on 2023-11-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0009_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='frecuencias',
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(2, 'Martes'), (1, 'Lunes'), (5, 'Viernes'), (4, 'Jueves'), (6, 'Sabado'), (3, 'Miercoles')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(2, 'Tarde'), (3, 'Noche'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(7, 'Cancelado'), (2, 'Vencido'), (3, 'Contratado'), (4, 'En Curso'), (6, 'Finalizado'), (5, 'Suspendido'), (1, 'Presupuestodo')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Eventual'), (2, 'Determinado')]),
        ),
    ]
