# Generated by Django 4.2.5 on 2023-11-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0010_remove_servicio_frecuencias_alter_frecuencia_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(3, 'Miercoles'), (2, 'Martes'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (1, 'Lunes')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(4, 'En Curso'), (7, 'Cancelado'), (3, 'Contratado'), (1, 'Presupuestodo'), (5, 'Suspendido'), (6, 'Finalizado'), (2, 'Vencido')]),
        ),
    ]
