# Generated by Django 4.2.5 on 2023-11-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_insumo_unidad_med_alter_sancion_tipo'),
        ('servicio', '0013_asistencia_alter_frecuencia_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frecuencia',
            name='empleados',
            field=models.ManyToManyField(related_name='frecuencias', to='core.empleado'),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(3, 'Miercoles'), (4, 'Jueves'), (2, 'Martes'), (1, 'Lunes'), (6, 'Sabado'), (5, 'Viernes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(3, 'Noche'), (1, 'Mañana'), (2, 'Tarde')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(7, 'Cancelado'), (2, 'Vencido'), (3, 'Contratado'), (6, 'Finalizado'), (4, 'En Curso'), (5, 'Suspendido'), (1, 'Presupuestodo')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Eventual'), (2, 'Determinado')]),
        ),
    ]
