# Generated by Django 4.2.5 on 2023-11-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0014_frecuencia_empleados_alter_frecuencia_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(6, 'Sabado'), (5, 'Viernes'), (3, 'Miercoles'), (2, 'Martes'), (4, 'Jueves'), (1, 'Lunes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(7, 'Cancelado'), (5, 'Suspendido'), (3, 'Contratado'), (4, 'En Curso'), (2, 'Vencido'), (6, 'Finalizado'), (1, 'Presupuestodo')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Determinado'), (1, 'Eventual')]),
        ),
    ]
