# Generated by Django 4.2.5 on 2023-11-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0016_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(4, 'Jueves'), (5, 'Viernes'), (3, 'Miercoles'), (2, 'Martes'), (1, 'Lunes'), (6, 'Sabado')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(2, 'Tarde'), (3, 'Noche'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Presupuestodo'), (5, 'Suspendido'), (2, 'Vencido'), (3, 'Contratado'), (6, 'Finalizado'), (7, 'Cancelado'), (4, 'En Curso')]),
        ),
    ]
