# Generated by Django 4.2.5 on 2023-11-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0017_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(5, 'Viernes'), (1, 'Lunes'), (6, 'Sabado'), (4, 'Jueves'), (3, 'Miercoles'), (2, 'Martes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(3, 'Noche'), (2, 'Tarde'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(4, 'En Curso'), (5, 'Suspendido'), (1, 'Presupuestado'), (2, 'Vencido'), (7, 'Cancelado'), (6, 'Finalizado'), (3, 'Contratado')]),
        ),
    ]
