# Generated by Django 4.2.5 on 2023-11-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_insumo_unidad_med_alter_sancion_tipo'),
        ('servicio', '0018_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(4, 'Jueves'), (1, 'Lunes'), (2, 'Martes'), (6, 'Sabado'), (5, 'Viernes'), (3, 'Miercoles')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='empleados',
            field=models.ManyToManyField(null=True, related_name='frecuencias', to='core.empleado'),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(2, 'Tarde'), (3, 'Noche'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(5, 'Suspendido'), (4, 'En Curso'), (2, 'Vencido'), (6, 'Finalizado'), (3, 'Contratado'), (1, 'Presupuestado'), (7, 'Cancelado')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Determinado'), (1, 'Eventual')]),
        ),
    ]
