# Generated by Django 4.2.5 on 2023-12-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_cliente_tipo_alter_cliente_tipopersona_and_more'),
        ('servicio', '0018_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(6, 'Sabado'), (1, 'Lunes'), (3, 'Miercoles'), (5, 'Viernes'), (4, 'Jueves'), (2, 'Martes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='empleados',
            field=models.ManyToManyField(null=True, related_name='frecuencias', to='core.empleado'),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(3, 'Noche'), (1, 'Mañana'), (2, 'Tarde')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Vencido'), (6, 'Finalizado'), (4, 'En Curso'), (7, 'Cancelado'), (5, 'Suspendido'), (3, 'Contratado'), (1, 'Presupuestado')]),
        ),
    ]
