# Generated by Django 4.2.5 on 2023-12-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0018_alter_frecuencia_dia_alter_frecuencia_empleados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(1, 'Lunes'), (3, 'Miercoles'), (2, 'Martes'), (5, 'Viernes'), (4, 'Jueves'), (6, 'Sabado')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(2, 'Tarde'), (3, 'Noche'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Presupuestado'), (5, 'Suspendido'), (6, 'Finalizado'), (4, 'En Curso'), (2, 'Vencido'), (3, 'Contratado'), (7, 'Cancelado')]),
        ),
    ]
