# Generated by Django 4.2.5 on 2023-12-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0019_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(1, 'Lunes'), (6, 'Sabado'), (5, 'Viernes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(4, 'En Curso'), (1, 'Presupuestado'), (5, 'Suspendido'), (7, 'Cancelado'), (2, 'Vencido'), (3, 'Contratado'), (6, 'Finalizado')]),
        ),
    ]
