# Generated by Django 4.2.5 on 2023-11-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0019_alter_frecuencia_dia_alter_frecuencia_empleados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(2, 'Martes'), (4, 'Jueves'), (6, 'Sabado'), (1, 'Lunes'), (3, 'Miercoles'), (5, 'Viernes')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(3, 'Noche'), (2, 'Tarde'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Vencido'), (7, 'Cancelado'), (1, 'Presupuestado'), (6, 'Finalizado'), (5, 'Suspendido'), (3, 'Contratado'), (4, 'En Curso')]),
        ),
    ]
