# Generated by Django 4.2.5 on 2023-12-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0019_alter_frecuencia_dia_alter_frecuencia_empleados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(6, 'Sabado'), (2, 'Martes'), (3, 'Miercoles'), (5, 'Viernes'), (1, 'Lunes'), (4, 'Jueves')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Presupuestado'), (4, 'En Curso'), (5, 'Suspendido'), (6, 'Finalizado'), (3, 'Contratado'), (7, 'Cancelado'), (2, 'Vencido')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(2, 'Determinado'), (1, 'Eventual')]),
        ),
    ]
