# Generated by Django 4.2.5 on 2023-12-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0020_alter_frecuencia_dia_alter_servicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(4, 'Jueves'), (6, 'Sabado'), (1, 'Lunes'), (2, 'Martes'), (5, 'Viernes'), (3, 'Miercoles')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(3, 'Noche'), (2, 'Tarde'), (1, 'Mañana')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(7, 'Cancelado'), (5, 'Suspendido'), (1, 'Presupuestado'), (2, 'Vencido'), (6, 'Finalizado'), (3, 'Contratado'), (4, 'En Curso')]),
        ),
    ]
