# Generated by Django 4.2.5 on 2023-12-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0020_alter_frecuencia_dia_alter_servicio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(1, 'Lunes'), (4, 'Jueves'), (6, 'Sabado'), (2, 'Martes'), (5, 'Viernes'), (3, 'Miercoles')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(6, 'Finalizado'), (2, 'Vencido'), (4, 'En Curso'), (7, 'Cancelado'), (3, 'Contratado'), (5, 'Suspendido'), (1, 'Presupuestado')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Eventual'), (2, 'Determinado')]),
        ),
    ]
