# Generated by Django 4.2.5 on 2023-12-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0021_alter_frecuencia_dia_alter_frecuencia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='dia',
            field=models.PositiveIntegerField(choices=[(2, 'Martes'), (5, 'Viernes'), (4, 'Jueves'), (3, 'Miercoles'), (1, 'Lunes'), (6, 'Sabado')]),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='turno',
            field=models.PositiveIntegerField(choices=[(3, 'Noche'), (1, 'Mañana'), (2, 'Tarde')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Presupuestado'), (7, 'Cancelado'), (3, 'Contratado'), (6, 'Finalizado'), (5, 'Suspendido'), (2, 'Vencido'), (4, 'En Curso')]),
        ),
    ]
